apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma
  namespace: argocd
spec:
  project: poc
  source:
    repoURL: 'https://github.com/JaimeHenaoChallange/kuma-lab.git'
    path: helm/kuma
    targetRevision: HEAD
    helm:
      valueFiles:
        - poc-kuma-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true