apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma
  namespace: argocd
spec:
  project: poc
  source:
    repoURL: 'https://github.com/JaimeHenaoChallange/kuma-lab.git'  # Cambia esto por la URL de tu repositorio
    targetRevision: HEAD  # O la rama específica que deseas usar
    path: ./kuma
  destination:
    server: 'https://kubernetes.default.svc'  # Para el clúster actual
    namespace: kuma-system  # Namespace donde está instalado Kuma
  syncPolicy:
    automated:
      prune: true  # Permite eliminar recursos que ya no están en el repositorio
      selfHeal: true  # Sincroniza automáticamente si hay desincronización