# Every `value` field must be a string containing valid JSON.
---
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: container-patch
  namespace: kuma-system
spec:
  sidecarPatch:
    - op: add
      path: /securityContext/capabilities
      value: '{"drop":["ALL"]}'
    - op: add
      path: /securityContext/seccompProfile
      value: '{"type":"RuntimeDefault"}'
    - op: add
      path: /securityContext/privileged
      value: "false"
    - op: add
      path: /securityContext/allowPrivilegeEscalation
      value: "false"
    - op: remove
      path: /resources/limits/ephemeral-storage
    - op: remove
      path: /resources/requests/ephemeral-storage
    - op: replace
      path: /resources/requests/cpu
      value: "100m"
    - op: replace
      path: /resources/requests/memory
      value: "256Mi"
    - op: replace
      path: /resources/limits/cpu
      value: "200m"
    - op: replace
      path: /resources/limits/memory
      value: "512Mi"
