kuma-resources:
  meshTrafficPermissions:
    - name: allow-app1-to-app2
      destinationKey: app.kubernetes.io/name
      destinationValue: app-2
      sources:
        - sourceKey: app.kubernetes.io/name
          sourceValue: app-1
  meshTrafficRoutes:
    - name: route-app1-to-app2
      sources:
        - match:
            kuma.io/service: app-1
      destinations:
        - match:
            kuma.io/service: app-2
      conf:
        split:
          - weight: 100
            destination:
              kuma.io/service: app-2
  meshTrafficLogs:
    - name: log-app1-to-app2
      sources:
        - match:
            kuma.io/service: app-1
      destinations:
        - match:
            kuma.io/service: app-2
      conf:
        backend: default