{{ if .Values.controlPlane.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuma.controlPlane.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "kuma.cpLabels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.controlPlane.service.annotations }}
    {{- if $value }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  type: NodePort
  ports:
    - port: 5680
      name: diagnostics
      appProtocol: http
      nodePort: 30080  # Puerto NodePort para el endpoint de métricas
    - port: 5681
      name: http-api-server
      appProtocol: http
      nodePort: 30081  # Puerto NodePort para el API HTTP
    - port: 5682
      name: https-api-server
      appProtocol: https
      nodePort: 30082  # Puerto NodePort para el API HTTPS
  selector:
    app: {{ include "kuma.name" . }}-control-plane
{{ end }}
